[toolchain]

[features]
seeds = false
skip-lint = false

[programs.devnet]
staking-app = "7SjKko5YDfUNwyjPd1eQSG8spdzbByhv1wVqgbMwbPPA"

[programs.localnet]
bank_app = "7xLqNTEnKTV3WgWzEXy4nmkeh4w2BtjkbcFrFiErvC51"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "/root/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
